language: node_js
node_js:
  - "7"
  - "8"
install:
  - npm install
script:
  - npm test
after_success:
  - '[ -z "$COVERALLS_REPO_TOKEN" ] && tap --coverage-report=text-lcov | ./node_modules/.bin/coveralls'